name: Deploy to GCP (Staging)

on:
  pull_request:
    branches:
      - '*'
jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/staging'  # Run only on push events to the 'staging' branch
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test
  deploy:
    name: This is deploy
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/staging'  # Run only on push events to the 'staging' branch